# This workflow will release a package at npmjs and at GitHub releases

name: Release

on:
  push:
    tags:
      - v*

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
        registry-url: https://registry.npmjs.org/
    - run: npm install
    - run: npm run build
    - run: npm publish --access=public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  github:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm pack
    - name: set release name, artifact, and message
      run: |
        echo "ARTIFACT_NAME=$(ls cocoda-sdk-*.tgz)" >> $GITHUB_ENV
    - id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: cocoda-sdk ${{ github.ref }}
        body: TODO
        draft: true
        prerelease: false
    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./$ARTIFACT_NAME
        asset_name: $ARTIFACT_NAME
        asset_content_type: application/gzip
